name: typewritertext
description: A simple typewriter text animation wrapper for flutter. Supports iOS, Android, web, Windows, macOS, and Linux.
version: 3.0.8
homepage: https://inidia.app
repository: https://github.com/Nialixus/typewritertext.git
issue_tracker: https://github.com/Nialixus/typewritertext/issues
funding:
  - https://ko-fi.com/nialixus
screenshots:
  - description: "TypeWriter Logo"
    path: logo.png
topics:
  - utility
  - animation

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
flutter: null
